services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  notifications:
    build: .
    ports:
      - "8083:8083"
    environment:
      AMQP_HOST: account-rabbitmq-1
      AMQP_USER: guest
      AMQP_PASS: guest
      SMTP_HOST: mailhog
      SMTP_PORT: "1025"
      SMTP_USER: ""
      SMTP_PASS: ""
      SMTP_FROM_ADDRESS: notifications@example.com
      PORT: "8083"
      AMQP_STARTUP_DELAY_SECS: "10"
    networks:
      - default
      - services_net

networks:
  services_net:
    external: true
