spring.application.name=connections
server.port=${PORT:8082}
spring.neo4j.uri=${NEO4J_URI:bolt://localhost:7687}
spring.neo4j.authentication.username=${NEO4J_USER:neo4j}
spring.neo4j.authentication.password=${NEO4J_PASSWORD:password}
spring.neo4j.connection-timeout=5s
spring.rabbitmq.host=${AMQP_HOST:localhost}
spring.rabbitmq.port=${AMQP_PORT:5672}
spring.rabbitmq.username=${AMQP_USER:guest}
spring.rabbitmq.password=${AMQP_PASS:guest}
